-- Create Database
CREATE DATABASE CustomerShoppingDB;

-- Use Database
USE CustomerShoppingDB;

-- Preview First 5 Records from Dataset
SELECT TOP 5 *
FROM customer_shopping_data;

-- Calculate Total Revenue Generated
SELECT 
    SUM(purchase_amount_usd) AS total_revenue
FROM customer_shopping_data;

-- Count Total Unique Customers
SELECT 
    COUNT(DISTINCT customer_id) AS total_customers
FROM customer_shopping_data;

-- Find Revenue Generated by Each Product Category
SELECT 
    category,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer_shopping_data
GROUP BY category
ORDER BY total_revenue DESC;

-- Calculate Average Spending by Gender
SELECT 
    gender,
    AVG(purchase_amount_usd) AS avg_spending
FROM customer_shopping_data
GROUP BY gender;

-- Identify Customers Who Used Discounts
-- and Spent More Than Average Purchase Amount
SELECT 
    customer_id,
    purchase_amount_usd
FROM customer_shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >= (
    SELECT AVG(purchase_amount_usd)
    FROM customer_shopping_data
);

-- Find Top 5 Highest Rated Products
SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating),2) AS average_product_rating
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY average_product_rating DESC;

-- Compare Average Purchase Amount by Shipping Type
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount_usd),2) AS avg_purchase
FROM customer_shopping_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Analyze Subscription Status with Customer Count,
-- Average Spending, and Total Revenue
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount_usd),2) AS avg_spend,
    ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer_shopping_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Find Top 5 Products with Highest Discount Usage Rate
SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE 
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
    2) AS discount_rate
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Segment Customers as New, Returning, or Loyal
-- Based on Previous Purchases
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_data
)

-- Count Number of Customers in Each Segment
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Rank Top Purchased Items Within Each Category
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,

        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank

    FROM customer_shopping_data
    GROUP BY category, item_purchased
)

-- Display Top 3 Most Purchased Items from Each Category
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Count Repeat Buyers Based on Subscription Status
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Analyze Revenue Generated by Different Age Groups
SELECT
    age_group,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer_shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC;